### ISSUE TITLE
Make failed with SunOS 5.10 sparc

### ISSUE THREAD

**Issue by riboseyim** [zeromq/libzmq#1866]
**SunOS 5.10 Generic_148888-01 sun4v sparc SUNW**
**version: zmq-4.1.2**

`# ./configure
checking for a BSD-compatible install... config/install-sh -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... config/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... nawk
checking whether make sets $(MAKE)... yes
checking how to create a ustar tar archive... plaintar
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for gcc option to accept ISO C99... -std=gnu99
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking whether gcc -std=gnu99 and cc understand -c and -o together... yes
checking for a sed that does not truncate output... /usr/bin/sed
checking for gawk... (cached) nawk
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for xmlto... no
checking for asciidoc... no
checking build system type... sparc-sun-solaris2.10
checking host system type... sparc-sun-solaris2.10
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) /usr/bin/sed
checking for grep that handles long lines and -e... /usr/xpg4/bin/grep
checking for egrep... /usr/xpg4/bin/grep -E
checking for fgrep... /usr/xpg4/bin/grep -F
checking for ld used by gcc -std=gnu99... /usr/ccs/bin/ld
checking if the linker (/usr/ccs/bin/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /usr/ccs/bin/nm -p
checking the name lister (/usr/ccs/bin/nm -p) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 786240
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert sparc-sun-solaris2.10 file names to sparc-sun-solaris2.10 format... func_convert_file_noop
checking how to convert sparc-sun-solaris2.10 file names to toolchain format... func_convert_file_noop
checking for /usr/ccs/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... dlltool
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... no
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/ccs/bin/nm -p output from gcc -std=gnu99 object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -std=gnu99 -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc -std=gnu99 supports -fno-rtti -fno-exceptions... no
checking for gcc -std=gnu99 option to produce PIC... -fPIC -DPIC
checking if gcc -std=gnu99 PIC flag -fPIC -DPIC works... yes
checking if gcc -std=gnu99 static flag -static works... no
checking if gcc -std=gnu99 supports -c -o file.o... yes
checking if gcc -std=gnu99 supports -c -o file.o... (cached) yes
checking whether the gcc -std=gnu99 linker (/usr/ccs/bin/ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... yes
checking dynamic linker characteristics... solaris2.10 ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... no
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/ccs/bin/ld
checking if the linker (/usr/ccs/bin/ld) is GNU ld... no
checking whether the g++ linker (/usr/ccs/bin/ld) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... no
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/ccs/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... solaris2.10 ld.so
checking how to hardcode library paths into programs... immediate
checking whether the C compiler works... yes
checking whether we are using Intel C compiler... no
checking whether we are using Sun Studio C compiler... no
checking whether we are using clang C compiler... no
checking whether we are using gcc >= 4 C compiler... no
checking whether the C++ compiler works... yes
checking whether we are using Intel C++ compiler... no
checking whether we are using Sun Studio C++ compiler... no
checking whether we are using clang C++ compiler... no
checking whether we are using gcc >= 4 C++ compiler... no
checking whether to enable debugging information... no
checking whether to enable code coverage... no
checking if TIPC is available and supports nonblocking connect... no
checking for socket in -lsocket... yes
checking for gethostbyname in -lnsl... yes
checking whether atomic operations can be used... yes
checking for pthread_create in -lpthread... no
checking for clock_gettime in -lrt... no
checking whether C++ compiler supports dso visibility... no
checking whether C++ compiler supports -mcpu=v9... yes
checking for asciidoc... no
checking for xmlto... no
checking whether to build documentation... no
checking whether to install manpages... yes
checking for suitable polling system... no suitable polling system found
configure: error: Unable to continue without polling system
# `

**Comment by bluca** [comment]
Hi,

Does the same problem happen with libzmq master from this repository?

I've got no way to test it, but in theory at least the "select" method should work.

Maybe it's the lack of "include <time.h>" in acinclude.m4? If I'm reading it correctly, the SunOS 5.1 manpage says it should be used: http://www.unix.com/man-page/sunos/3c/select/

**Comment by zijingshanke** [comment]
libzmq master is working !!

but .....

checking for stdbool.h that conforms to C99... no
checking for _Bool... no
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking for size_t... yes
checking for ssize_t... yes
checking whether time.h and sys/time.h may both be included... yes
checking for uint32_t... yes
checking for working volatile... yes
./configure: line 19333: syntax error near unexpected token `sodium,'
./configure: line 19333: `    PKG_CHECK_MODULES(sodium, libsodium, libsodium_found=yes,'
xm-zyite-col02#

**Comment by bluca** [comment]
Do you have pkg-config installed?

**Comment by zijingshanke** [comment]
I have pkg-config.
Most of my servers  are Linux based,and no any problem.
For some reasons,still have several based on SunOS 5.1.

**Comment by zijingshanke** [comment]
** And in another server,I can configure success !  But make failed :ipc_listener.cpp:110: error: `mkdtemp' undeclared **  
**SunOS  5.10 Generic_118833-17 sun4us sparc FJSV,GPUZC-M**

hecking whether SOCK_CLOEXEC is supported... no
checking whether SO_KEEPALIVE is supported... yes
checking whether TCP_KEEPCNT is supported... no
checking whether TCP_KEEPIDLE is supported... no
checking whether TCP_KEEPINTVL is supported... no
checking whether TCP_KEEPALIVE is supported... no
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/libzmq.pc
config.status: creating doc/Makefile
config.status: creating builds/Makefile
config.status: creating builds/msvc/Makefile
config.status: creating packaging/redhat/zeromq.spec
config.status: creating src/platform.hpp
config.status: executing depfiles commands
config.status: executing libtool commands

**make**

  CXX    src/src_libzmq_la-gssapi_server.lo
  CXX    src/src_libzmq_la-io_object.lo
  CXX    src/src_libzmq_la-io_thread.lo
  CXX    src/src_libzmq_la-ip.lo
  CXX    src/src_libzmq_la-ipc_address.lo
  CXX    src/src_libzmq_la-ipc_connecter.lo
  CXX    src/src_libzmq_la-ipc_listener.lo
src/ipc_listener.cpp: In static member function `static int 
   zmq::ipc_listener_t::create_wildcard_address(std::string&)':
src/ipc_listener.cpp:102: error: `data' undeclared (first use this function)
src/ipc_listener.cpp:102: error: (Each undeclared identifier is reported only 
   once for each function it appears in.)
src/ipc_listener.cpp:110: error: `mkdtemp' undeclared (first use this function)
make[1]: *** [src/src_libzmq_la-ipc_listener.lo] Error 1
make[1]: Leaving directory `/slview/install/libzmq-master'
make: *** [all-recursive] Error 1

**Comment by bluca** [comment]
Regarding the first machine, are you absolutely certain that pkg-config is installed and available? If you run `pkg-config --version`, what's the output? I ask because that's exactly the error you would get without pkg-config.

On the second machine, from a quick search it looks like mkdtemp is not available on Solaris.

Could you please run: `git revert b6080a798` and solve the conflict (it's trivial to do so, just a test) and try again?

**Comment by zijingshanke** [comment]
both
$ pkg-config --version
0.15.0

**Comment by bluca** [comment]
That is strange. I'm afraid I really don't know the SunOS platform, so besides checking that pkg-config is available I can't tell what could be the problem on the other server.

Have you tried the git revert to get past the compilation issue?

**Comment by zijingshanke** [comment]
I tried `git revert b6080a798`:

configure success,make failed condition_variable.hpp

configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/libzmq.pc
config.status: creating doc/Makefile
config.status: creating builds/Makefile
config.status: creating builds/msvc/Makefile
config.status: creating packaging/redhat/zeromq.spec
config.status: creating src/platform.hpp
config.status: src/platform.hpp is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
xm-zyite-col02# make
Making all in doc
make[1]: Entering directory `/slview/install/libzmq/doc'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/slview/install/libzmq/doc'
make[1]: Entering directory `/slview/install/libzmq'
  CXX    src/src_libzmq_la-address.lo
  CXX    src/src_libzmq_la-client.lo
  CXX    src/src_libzmq_la-clock.lo
  CXX    src/src_libzmq_la-ctx.lo
  CXX    src/src_libzmq_la-curve_client.lo
  CXX    src/src_libzmq_la-curve_server.lo
  CXX    src/src_libzmq_la-dealer.lo
  CXX    src/src_libzmq_la-devpoll.lo
  CXX    src/src_libzmq_la-dish.lo
  CXX    src/src_libzmq_la-dist.lo
  CXX    src/src_libzmq_la-epoll.lo
  CXX    src/src_libzmq_la-err.lo
  CXX    src/src_libzmq_la-fq.lo
  CXX    src/src_libzmq_la-gssapi_mechanism_base.lo
  CXX    src/src_libzmq_la-gssapi_client.lo
  CXX    src/src_libzmq_la-gssapi_server.lo
  CXX    src/src_libzmq_la-io_object.lo
  CXX    src/src_libzmq_la-io_thread.lo
  CXX    src/src_libzmq_la-ip.lo
  CXX    src/src_libzmq_la-ipc_address.lo
  CXX    src/src_libzmq_la-ipc_connecter.lo
  CXX    src/src_libzmq_la-ipc_listener.lo
  CXX    src/src_libzmq_la-kqueue.lo
  CXX    src/src_libzmq_la-lb.lo
  CXX    src/src_libzmq_la-mailbox.lo
  CXX    src/src_libzmq_la-mailbox_safe.lo
In file included from src/mailbox_safe.hpp:44,
                 from src/mailbox_safe.cpp:31:
src/condition_variable.hpp: In member function `int 
   zmq::condition_variable_t::wait(zmq::mutex_t*, int)':
src/condition_variable.hpp:170: warning: assignment to `long int' from `double'
src/condition_variable.hpp:170: warning: argument to `long int' from `double'
make[1]: *** [src/src_libzmq_la-mailbox_safe.lo] Error 1
make[1]: Leaving directory `/slview/install/libzmq'
make: *** [all-recursive] Error 1

**Comment by bluca** [comment]
Could you please try from this branch of mine?

```
git remote add bluca https://github.com/bluca/libzmq.git
git fetch bluca
git checkout solaris_fixes
```

I've got a couple of changes that should fix that problem and the one caused by the commit you reverted. But I have no Solaris box to test them (trying to setup a VM with Solaris 10 x86) so I wanted to be sure it works before sending them. Thanks!

**Comment by zijingshanke** [comment]
`bluca solaris_fixes branch `

`make      `
Making all in doc
make[1]: Entering directory `/slview/install/libzmqfix/doc'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/slview/install/libzmqfix/doc'
make[1]: Entering directory `/slview/install/libzmqfix'
  CXX    src/src_libzmq_la-address.lo
  CXX    src/src_libzmq_la-client.lo
  CXX    src/src_libzmq_la-clock.lo
  CXX    src/src_libzmq_la-ctx.lo
  CXX    src/src_libzmq_la-curve_client.lo
  CXX    src/src_libzmq_la-curve_server.lo
  CXX    src/src_libzmq_la-dealer.lo
  CXX    src/src_libzmq_la-devpoll.lo
  CXX    src/src_libzmq_la-dish.lo
  CXX    src/src_libzmq_la-dist.lo
  CXX    src/src_libzmq_la-epoll.lo
  CXX    src/src_libzmq_la-err.lo
  CXX    src/src_libzmq_la-fq.lo
  CXX    src/src_libzmq_la-gssapi_mechanism_base.lo
  CXX    src/src_libzmq_la-gssapi_client.lo
  CXX    src/src_libzmq_la-gssapi_server.lo
  CXX    src/src_libzmq_la-io_object.lo
  CXX    src/src_libzmq_la-io_thread.lo
  CXX    src/src_libzmq_la-ip.lo
  CXX    src/src_libzmq_la-ipc_address.lo
  CXX    src/src_libzmq_la-ipc_connecter.lo
  CXX    src/src_libzmq_la-ipc_listener.lo
src/ipc_listener.cpp: In static member function `static int 
   zmq::ipc_listener_t::create_wildcard_address(std::string&, std::string&)':
src/ipc_listener.cpp:103: error: `data' undeclared (first use this function)
src/ipc_listener.cpp:103: error: (Each undeclared identifier is reported only 
   once for each function it appears in.)
make[1]: *** [src/src_libzmq_la-ipc_listener.lo] Error 1
make[1]: Leaving directory `/slview/install/libzmqfix'
make: *** [all-recursive] Error 1

**Comment by bluca** [comment]
The data() method of std::vector is new in C++ 11, which I guess is not available in the GCC version shipped in Solaris 10.
Unfortunately I just can't seem to get gcc to build in strict -std=c++98 mode, not even with -pedantic and -pedantic-errors, so it's a bit hard to come up with a solution that would work.
I'll try and get that VM up and running.

**Comment by bluca** [comment]
@zijingshanke - could you please pull from my branch and try again? I got a Solaris 10 x86 up and running, and was able to build after those new fixes.

Also I was able to get past the pkg-config issue by using a newer version of pkg.m4 macro file, after installing pkg-config with pkgutil -y -i pkgconfig (OpenCSW project). Maybe the server where it works has the same newer version?

**Comment by bluca** [comment]
@riboseyim - if you try now from the 4.1 repository it should all work:
https://github.com/zeromq/zeromq4-1/pull/117

**Comment by riboseyim** [comment]
Thanks !

but I'm afraid still have some problem:

configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/libzmq.pc
config.status: creating doc/Makefile
config.status: creating builds/msvc/Makefile
config.status: creating builds/redhat/zeromq.spec
config.status: creating src/platform.hpp
config.status: executing depfiles commands
config.status: executing libtool commands
xm-zyite-col02# make
Making all in doc
make[1]: Entering directory `/slview/install/libzmqfix/doc'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/slview/install/libzmqfix/doc'
make[1]: Entering directory `/slview/install/libzmqfix'
  CXX    src/libzmq_la-address.lo
  CXX    src/libzmq_la-clock.lo
  CXX    src/libzmq_la-ctx.lo
In file included from src/socket_base.hpp:41,
                 from src/ctx.cpp:42:
src/poller.hpp:56:2: #error None of the ZMQ_USE_* macros defined
In file included from src/ctx.cpp:42:
src/socket_base.hpp:102: error: `poller_t' was not declared in this scope
src/socket_base.hpp:102: error: `poller_' was not declared in this scope
src/socket_base.hpp:102: error: invalid data member initialization
src/socket_base.hpp:102: error: (use `=' to initialize static data members)
src/socket_base.hpp:102: error: variable or field `start_reaping' declared void
src/socket_base.hpp:243: error: syntax error before `*' token
src/socket_base.hpp:244: error: syntax error before `::' token
In file included from src/ctx.cpp:43:
src/io_thread.hpp:74: error: syntax error before `*' token
src/io_thread.hpp:88: error: syntax error before `::' token
src/io_thread.hpp:91: error: syntax error before `*' token
In file included from src/ctx.cpp:44:
src/reaper.hpp:72: error: syntax error before `::' token
src/reaper.hpp:75: error: syntax error before `*' token
src/ctx.cpp: In function `int clipped_maxsocket(int)':
src/ctx.cpp:60: error: no class template named `poller_t' in `zmq'
src/ctx.cpp:60: error: no class template named `poller_t' in `zmq'
src/ctx.cpp:62: error: no class template named `poller_t' in `zmq'
make[1]: *** [src/libzmq_la-ctx.lo] Error 1
make[1]: Leaving directory `/slview/install/libzmqfix'
make: *** [all-recursive] Error 1

**The last commit:**
` git log`
commit dd077bc2b2db192ee6abe41f8070817fed9c7990
Merge: 7105025 e488df7
Author: Constantin Rack <c-rack@users.noreply.github.com>
Date:   Wed Apr 13 22:56:53 2016 +0200

    Merge pull request #117 from bluca/solaris_fixes
    
    Problem: build broken on Solaris 10

**Comment by bluca** [comment]
What is the output of ./configure ?

**Comment by riboseyim** [comment]
./configure > configure3.log
./configure: line 5275: PKG_PROG_PKG_CONFIG: command not found
configure: WARNING: You are building an unreleased version of 0MQ and asciidoc or xmlto are not installed.
configure: WARNING: Documentation will not be built and manual pages will not be installed.

**Comment by riboseyim** [comment]
checking for a BSD-compatible install... config/install-sh -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... config/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... nawk
checking whether make sets $(MAKE)... yes
checking how to create a ustar tar archive... plaintar
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for gcc option to accept ISO C99... -std=gnu99
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking whether gcc -std=gnu99 and cc understand -c and -o together... yes
checking for a sed that does not truncate output... /usr/bin/sed
checking for gawk... (cached) nawk
checking for xmlto... no
checking for asciidoc... no
checking build system type... sparc-sun-solaris2.10
checking host system type... sparc-sun-solaris2.10
checking for a sed that does not truncate output... (cached) /usr/bin/sed
checking for grep that handles long lines and -e... /usr/xpg4/bin/grep
checking for egrep... /usr/xpg4/bin/grep -E
checking for fgrep... /usr/xpg4/bin/grep -F
checking for ld used by gcc -std=gnu99... /usr/ccs/bin/ld
checking if the linker (/usr/ccs/bin/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /usr/ccs/bin/nm -p
checking the name lister (/usr/ccs/bin/nm -p) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 786240
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking for /usr/ccs/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for ar... ar
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/ccs/bin/nm -p output from gcc -std=gnu99 object... ok
checking how to run the C preprocessor... gcc -std=gnu99 -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether g++ accepts -g... (cached) yes
checking dependency style of g++... (cached) gcc3
checking how to run the C++ preprocessor... g++ -E
checking for objdir... .libs
checking if gcc -std=gnu99 supports -fno-rtti -fno-exceptions... no
checking for gcc -std=gnu99 option to produce PIC... -fPIC -DPIC
checking if gcc -std=gnu99 PIC flag -fPIC -DPIC works... yes
checking if gcc -std=gnu99 static flag -static works... no
checking if gcc -std=gnu99 supports -c -o file.o... yes
checking if gcc -std=gnu99 supports -c -o file.o... (cached) yes
checking whether the gcc -std=gnu99 linker (/usr/ccs/bin/ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... yes
checking dynamic linker characteristics... solaris2.10 ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... no
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for ld used by g++... /usr/ccs/bin/ld
checking if the linker (/usr/ccs/bin/ld) is GNU ld... no
checking whether the g++ linker (/usr/ccs/bin/ld) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... no
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/ccs/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... solaris2.10 ld.so
checking how to hardcode library paths into programs... immediate
checking whether the C compiler works... yes
checking whether we are using Intel C compiler... no
checking whether we are using Sun Studio C compiler... no
checking whether we are using clang C compiler... no
checking whether we are using gcc >= 4 C compiler... no
checking whether the C++ compiler works... yes
checking whether we are using Intel C++ compiler... no
checking whether we are using Sun Studio C++ compiler... no
checking whether we are using clang C++ compiler... no
checking whether we are using gcc >= 4 C++ compiler... no
checking whether to enable debugging information... no
checking whether to enable code coverage... no
checking if TIPC is available and supports nonblocking connect... no
checking for socket in -lsocket... yes
checking for gethostbyname in -lnsl... yes
checking whether atomic operations can be used... yes
checking for pthread_create in -lpthread... yes
checking for clock_gettime in -lrt... yes
checking whether C++ compiler supports dso visibility... no
checking whether C++ compiler supports -mcpu=v9... yes
checking for asciidoc... no
checking for xmlto... no
checking whether to build documentation... no
checking whether to install manpages... no
checking for suitable polling system... using poll
checking for ANSI C header files... (cached) yes
checking errno.h usability... yes
checking errno.h presence... yes
checking for errno.h... yes
checking time.h usability... yes
checking time.h presence... yes
checking for time.h... yes
checking for unistd.h... (cached) yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking netinet/tcp.h usability... yes
checking netinet/tcp.h presence... yes
checking for netinet/tcp.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking ifaddrs.h usability... no
checking ifaddrs.h presence... no
checking for ifaddrs.h... no
checking sys/uio.h usability... yes
checking sys/uio.h presence... yes
checking for sys/uio.h... yes
checking sys/eventfd.h usability... no
checking sys/eventfd.h presence... no
checking for sys/eventfd.h... no
checking whether SO_PEERCRED is declared... no
checking whether LOCAL_PEERCRED is declared... no
checking for stdbool.h that conforms to C99... no
checking for _Bool... no
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking for size_t... yes
checking for ssize_t... yes
checking whether time.h and sys/time.h may both be included... yes
checking for uint32_t... yes
checking for working volatile... yes
configure: Using tweetnacl for CURVE security
checking "with_norm_ext = no"... checking how to enable additional warnings for C++ compiler... -Wall
checking how to turn warnings to errors in C++ compiler... -Werror
checking how to enable strict standards compliance in C++ compiler... -pedantic
checking return type of signal handlers... void
checking for perror... yes
checking for gettimeofday... yes
checking for clock_gettime... yes
checking for memset... yes
checking for socket... yes
checking for getifaddrs... no
checking for freeifaddrs... no
checking for fork... yes
checking alloca.h usability... yes
checking alloca.h presence... yes
checking for alloca.h... yes
checking whether SOCK_CLOEXEC is supported... no
checking whether SO_KEEPALIVE is supported... yes
checking whether TCP_KEEPCNT is supported... no
checking whether TCP_KEEPIDLE is supported... no
checking whether TCP_KEEPINTVL is supported... no
checking whether TCP_KEEPALIVE is supported... no
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/libzmq.pc
config.status: creating doc/Makefile
config.status: creating builds/msvc/Makefile
config.status: creating builds/redhat/zeromq.spec
config.status: creating src/platform.hpp
config.status: src/platform.hpp is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands

**Comment by riboseyim** [comment]
`pkg-config --version
`0.15.0

whereis pkg-config
pkg-config: /usr/bin/pkg-config

`ldd /usr/bin/pkg-config`
        libc.so.1 =>     /usr/lib/libc.so.1
        libm.so.2 =>     /usr/lib/libm.so.2
        /platform/FJSV,GPUZC-M/lib/libc_psr.so.1

**Comment by bluca** [comment]
`checking for suitable polling system... using poll`

It did find a polling mechanism, which was the error it complaied about before. Could you please try again with make clean && make ?

I think the problem with pkg-config is that the pkg.m4 macro file shipped in Solaris is just too old and broken :-( If you pick a more recent pkg.m4 and put it somewhere aclocal can find it, it will work.

But it should be able to work anyway on 4.1, since pkg-config is required only if you are building with libsodium or libpgm.
