### ISSUE TITLE
Fails to compile with clang

### ISSUE THREAD

**Issue by atweiden** [zeromq/libzmq#1363]
My build configuration:

```
$ clang --version
clang version 3.5.1 (tags/RELEASE_351/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
```

```
  ./autogen.sh
  CC=clang CXX=clang CXXFLAGS=-stdlib=libstdc++ LDLIBS=-lstdc++ ./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --libexecdir=/usr/lib/zeromq \
    --sysconfdir=/etc \
    --sharedstatedir=/usr/share/zeromq \
    --localstatedir=/var/lib/zeromq \
    --with-gnu-ld \
    --with-pgm \
    --with-libsodium
  CC=clang CXX=clang CXXFLAGS=-stdlib=libstdc++ LDLIBS=-lstdc++ make
```

The error as of https://github.com/zeromq/libzmq/commit/1a5ced9f474edbb33c39a65fdb62c0a1e87e32ca:

```
  CXX      src/src_libzmq_la-address.lo
In file included from src/address.cpp:21:
In file included from ./src/address.hpp:23:
In file included from /bin/../lib64/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../include/c++/4.9.2/string:38:
In file included from /bin/../lib64/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../include/c++/4.9.2/x86_64-unknown-linux-gnu/bits/c++config.h:430:
In file included from /bin/../lib64/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../include/c++/4.9.2/x86_64-unknown-linux-gnu/bits/os_defines.h:39:
/usr/include/features.h:328:4: error: _FORTIFY_SOURCE requires compiling with optimization (-O)
      [-Werror,-W#warnings]
#  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
   ^
1 error generated.
Makefile:2765: recipe for target 'src/src_libzmq_la-address.lo' failed
make[1]: *** [src/src_libzmq_la-address.lo] Error 1
make[1]: Leaving directory '/home/user/pkgbuilds/zeromq-git/src/zeromq'
Makefile:3393: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

**Comment by rodgert** [comment]
Is this on Arch linux? some other flavor?

**Comment by rodgert** [comment]
FWIW, on Ubuntu14.04 with Clang3.5, libzmq builds without issue.

**Comment by atweiden** [comment]
It is Arch

**Comment by rodgert** [comment]
I can also check it on Fedora later tonight, but I don't think it is a
clang issue (works with stock Ubuntu 14.04 and Clang3.5),

**Comment by rodgert** [comment]
I tried it with - 

$ pacman -Q clang gcc glibc linux
clang 3.5.1-1
gcc 4.9.2-2
glibc 2.20-6
linux 3.18.4-1
$ uname -a
Linux localhost 3.18.4-1-ARCH #1 SMP PREEMPT Tue Jan 27 20:45:02 CET 2015 x86_64 GNU/Linux

And was not able to reproduce this issue.

**Comment by atweiden** [comment]
Interesting.  I haven't done anything fancy to the build configuration. I am on the latest released kernel 3.18.6, dunno if that would matter.

Were you sure to build using clang, e.g. `CC=clang CXX=clang CXXFLAGS=-stdlib=libstdc++ LDLIBS=-lstdc++`?

**Comment by rodgert** [comment]
I did both with specifying only CC=clang CXX=clang++ and with fully
specifying libstdc++ as well, same results.
