### PR TITLE
Problem: 4.2.0 won't compile on AIX 7.1

### LINKED ISSUE #2234: 4.2.0 won't compile on AIX 7.1
zeromq 4.1.6 compiles on my AIX box and passes all tests. However, attempting to build zeromq 4.2.0 I find compile problems. Details follow:

$ xlC -qversion
IBM XL C/C++ for AIX, V12.1 (5765-J02, 5725-C72)
Version: 12.01.0000.0000
$ oslevel
7.1.0.0

$ configure CC=xlc CXX=xlC
$ make
Making all in doc
make[1]: Entering directory `/home/meb/zeromq-4.2.0/doc'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/meb/zeromq-4.2.0/doc'
make[1]: Entering directory `/home/meb/zeromq-4.2.0'
  CXX      src/src_libzmq_la-proxy.lo
"src/proxy.cpp", line 157.34: 1540-0217 (S) "rtnevents" is not a member of "struct zmq_pollitem_t".
"src/proxy.cpp", line 188.22: 1540-0217 (S) "rtnevents" is not a member of "struct zmq_pollitem_t".
"src/proxy.cpp", line 189.51: 1540-0217 (S) "rtnevents" is not a member of "struct zmq_pollitem_t".
"src/proxy.cpp", line 197.22: 1540-0217 (S) "rtnevents" is not a member of "struct zmq_pollitem_t".
"src/proxy.cpp", line 198.25: 1540-0217 (S) "rtnevents" is not a member of "struct zmq_pollitem_t".
make[1]: *** [src/src_libzmq_la-proxy.lo] Error 1
make[1]: Leaving directory `/home/meb/zeromq-4.2.0'
make: *** [all-recursive] Error 1

### PR DESCRIPTION
**Pull request by bluca**
Solution: restore inclusion of poll.h if using poll before zmq.h as
it was originally, as AIX redefines the POSIX structures and provides
compatibility macros.
Also add alternative aliases for 32 bit AIX's pollitem struct:
  events -> reqevents
  revents -> rtnevents

Partially fixes #2234

### CODE REVIEW

**Comment by c-rack** [comment]
@bluca `Partially fixes #2234` will probably close that issue once merged, is this intended?

**Comment by bluca** [comment]
It's fine, I can reopen it :-)

**Comment by c-rack** [comment]
OK, here you are :-)
