### ISSUE TITLE
Build failing on CI, on Linux

### ISSUE THREAD

**Issue by paddor** [zeromq/libzmq#1720]
Currently, libzmq CI build is [failing](https://travis-ci.org/zeromq/libzmq/jobs/103594213).

I'm also getting the same error in czmq-ffi-gen: [here](https://travis-ci.org/paddor/czmq-ffi-gen/jobs/103648750).

```
[...]
  CXX    src/src_libzmq_la-vmci.lo
  CXX    src/src_libzmq_la-vmci_address.lo
  CXX    src/src_libzmq_la-vmci_connecter.lo
  CXX    src/src_libzmq_la-vmci_listener.lo
  CXX    src/src_libzmq_la-xpub.lo
  CXX    src/src_libzmq_la-xsub.lo
  CXX    src/src_libzmq_la-zmq.lo
src/zmq.cpp: In function ‘int s_sendmsg(zmq::socket_base_t*, zmq_msg_t*, int)’:
src/zmq.cpp:354:24: error: ‘INT_MAX’ was not declared in this scope
src/zmq.cpp: In function ‘int s_recvmsg(zmq::socket_base_t*, zmq_msg_t*, int)’:
src/zmq.cpp:466:24: error: ‘INT_MAX’ was not declared in this scope
src/zmq.cpp:467:1: error: control reaches end of non-void function [-Werror=return-type]
src/zmq.cpp: In function ‘int s_sendmsg(zmq::socket_base_t*, zmq_msg_t*, int)’:
src/zmq.cpp:355:1: error: control reaches end of non-void function [-Werror=return-type]
cc1plus: all warnings being treated as errors
make[1]: *** [src/src_libzmq_la-zmq.lo] Error 1
make[1]: Leaving directory `/home/travis/src/libzmq'
make: *** [all-recursive] Error 1
```

**Comment by c-rack** [comment]
Caused by #1719. Seems we forgot a `#include <climits>"`.
I'll send a PR once the build is green on my branch.
