### ISSUE TITLE
libzeromq can not build on RedHat4.8

### ISSUE THREAD

**Issue by yokarno** [zeromq/libzmq#2487]
The compile error is:
  CXX      src/src_libzmq_la-ip.lo
src/ip.cpp: In function `void zmq::set_ip_type_of_service(zmq::fd_t, int)':
src/ip.cpp:181: error: `IPV6_TCLASS' was not declared in this scope
src/ip.cpp:181: warning: unused variable 'IPV6_TCLASS'
make[1]: *** [src/src_libzmq_la-ip.lo] Error 1

could you please check this issue ? 

or can i make change for this ?  how about the license if i modify the code?

**Comment by bluca** [comment]
What version are you running? This should only happen on 4.2.1, and be fixed in 4.2.2

**Comment by yokarno** [comment]
yes，i use 4.2.1，but where can i get 4.2.2?

**Comment by bluca** [comment]
Same place you get 4.2.1:

https://github.com/zeromq/libzmq/releases
https://github.com/zeromq/libzmq/releases/tag/v4.2.2

**Comment by bluca** [comment]
Regarding the license, it's LGPL-3 + static exception + tivoization clause exception as you can see in COPYING and COPYING.LESSER

**Comment by yokarno** [comment]
yes,got it, solved, thanks a lot.
it's my fault to not find and get the latest version

**Comment by bluca** [comment]
No problem
