### ISSUE TITLE
Cannot build 4.3.3 with mingw

### ISSUE THREAD

**Issue by jagerman** [zeromq/libzmq#4044]
# Issue description

zeromq 4.3.3 fails to build with mingw, where zeromq 4.3.2 was fine:

```
tests/testutil.hpp:105:15: error: conflicting declaration of C function ‘int closesocket(int)’
  105 | #define close closesocket
      |               ^~~~~~~~~~~
In file included from tests/../src/windows.hpp:54,
                 from tests/testutil.hpp:43,
                 from tests/testutil_unity.hpp:34,
                 from tests/testutil_unity.cpp:29:
/usr/share/mingw-w64/include/winsock2.h:1005:34: note: previous declaration ‘int closesocket(SOCKET)’
 1005 |   WINSOCK_API_LINKAGE int WSAAPI closesocket(SOCKET s);
      |                                  ^~~~~~~~~~~
```

Everything builds fine if I delete the:

`#define close closesocket`

referenced above, but I don't whether this is some hack needed for other Windows compilers (e.g. MSVC).  It *does* seem like a pretty dangerous thing to define in a header, though.

Since that define was there in 4.3.2, I am not sure why this started failing in 4.3.3: perhaps some test includes shuffled around?

(Looking at it more closely, it seems testutil.hpp has quite a bit of other Windows-related cruft that isn't needed at all since it has already included ../src/windows.hpp).

# Environment

* libzmq version 4.3.3
* OS: Debian linux
* $ x86_64-w64-mingw32-gcc --version
x86_64-w64-mingw32-gcc (GCC) 10-posix 20200525

**Comment by sigiesec** [comment]
I am pretty sure that this can't simply be removed when building against the Windows SDK (not dependent on the compiler probably).

There are maybe nicer ways to do this than via this preprocessor define. This seemed to be the simplest way to fit in the Windows SDK with the somehow Posix-biased code.

A PR improving this or at least fixing mingw would be definitely welcome!

I think we have a mingw CI job, I wonder if that's broken without notice, or something ia different there.

**Comment by 0x0badc0de** [comment]
Got the same issue, just disabled tests by passing `-DBUILD_TESTS=OFF` to cmake.
