### ISSUE TITLE
2.0.9 zip fails to compile with MinGW GCC 4.5.0 (Windows)

### ISSUE THREAD

**Issue by luislavena** [zeromq/libzmq#66]
using GCC 4.5.0 (TDM) in 32 bits mode. Using .zip package

<pre><code>mkdir build
cd build
sh -c "../configure"
</code></pre>

Fails with the following:

<pre><code>
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../../src -Werror -pedantic -Wall -D_REENTRANT -D_THREAD_SAFE -g -O2 -MT libzmq_la-msg_store.lo -MD -MP -MF .deps/libzmq_la-msg_store.Tpo -c ../../src/msg_store.cpp  -DDLL_EXPORT -DPIC -o .libs/libzmq_la-msg_store.o
cc1plus.exe: warnings being treated as errors
../../src/msg_store.cpp: In member function 'void zmq::msg_store_t::fill_buf(char*, int64_t)':
../../src/msg_store.cpp:253:9: error: ISO C++ 1998 does not support 'long long'
../../src/msg_store.cpp: In member function 'void zmq::msg_store_t::save_write_buf()':
../../src/msg_store.cpp:279:9: error: ISO C++ 1998 does not support 'long long'
make[2]: *** [libzmq_la-msg_store.lo] Error 1
</code></pre>
