### ISSUE TITLE
compilation failure on OSX10.12

### ISSUE THREAD

**Issue by hkiel** [zeromq/libzmq#2750]
# Issue description
Compilation fails on my OSX10.12 with Xcode 8.3.3:
```
  CXX      src/src_libzmq_la-mailbox_safe.lo
In file included from src/mailbox_safe.hpp:43:0,
                 from src/mailbox_safe.cpp:31:
src/condition_variable.hpp: In member function 'int zmq::condition_variable_t::wait(zmq::mutex_t*, int)':
src/condition_variable.hpp:219:31: error: 'CLOCK_MONOTONIC' was not declared in this scope
                 clock_gettime(CLOCK_MONOTONIC, &timeout);
                               ^~~~~~~~~~~~~~~
src/condition_variable.hpp:219:56: error: 'clock_gettime' was not declared in this scope
                 clock_gettime(CLOCK_MONOTONIC, &timeout);
                                                        ^
gmake[1]: *** [Makefile:3622: src/src_libzmq_la-mailbox_safe.lo] Error 1
gmake[1]: Leaving directory '/Users/foo/src/libzmq'
gmake: *** [Makefile:4271: all-recursive] Error 1

```

# Environment
* libzmq version (commit hash if unreleased):  git 2e16788
* OS:  OSX10.12 with Xcode8.3.3

**Comment by sigiesec** [comment]
Could you try https://github.com/sigiesec/libzmq/tree/fix-macos-sierra ?

**Comment by hkiel** [comment]
@sigiesec Not better. I have the impression that my system is somehow screwed up (updating from Mavericks->ElCapitan->Sierra and some iterations of Xcode and its CommandLineTools). My /usr/include/time.h does not define `CLOCK_MONOTONIC`, though it should on Xcode8.3.3 with CommandLineTools for macOS10.12 ...

**Comment by bluca** [comment]
I remember some work went in to fix OSX when CLOCK_MONOTONIC was finally added... it was a bit of a pain.

We should really refactor all of that and use autoconf, something like:

https://github.com/mobile-shell/mosh/commit/b0facb55c48c1e84d1a855ea862d5381667effa3

**Comment by Asmod4n** [comment]
Works fine with a clean install of 10.13 and Xcode

**Comment by michaelld** [comment]
The latest GIT master (020b0bed) builds cleanly for me on 10.8 (gcc 4.2) and 10.12 (clang 9.0). IMHO this issue can be safely closed, since the OP admits his install was messed up.

**Comment by bluca** [comment]
Ok, thanks for the report
