### ISSUE TITLE
Error when compiling with MinGW due to usage of MS-specific __except keyword

### ISSUE THREAD

**Issue by Rush** [zeromq/libzmq#3586]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description

Trying to compile libzmq with MinGW - the issue is fairly obvious. `__except` should not have gone through a code review as it's a Microsoft specific extension.

https://github.com/zeromq/libzmq/blame/aac3cd4d93d288b29b71806c2478a947d66238b6/src/thread.cpp#L136

```
src/thread.cpp:128: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(push)                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                             
src/thread.cpp:129: warning: ignoring #pragma warning  [-Wunknown-pragmas]                                                                                                                                                                                   
 #pragma warning(disable : 6320 6322)                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                             
src/thread.cpp:138: warning: ignoring #pragma warning  [-Wunknown-pragmas]                                                                                                                                                                                   
 #pragma warning(pop)                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                             
src/thread.cpp: In member function 'void zmq::thread_t::applyThreadName()':                                                                                                                                                                                  
src/thread.cpp:136:5: error: expected 'catch' before '__except'                                                                                                                                                                                              
     __except (EXCEPTION_CONTINUE_EXECUTION) {                                                                                                                                                                                                               
     ^~~~~~~~                                                                                                                                                                                                                                                
src/thread.cpp:136:5: error: expected '(' before '__except'                                                                                                                                                                                                  
     __except (EXCEPTION_CONTINUE_EXECUTION) {                                                                                                                                                                                                               
     ^~~~~~~~                                                                                                                                                                                                                                                
     (                                                                                                                                                                                                                                                       
src/thread.cpp:136:5: error: expected type-specifier before '__except'                                                                                                                                                                                       
     __except (EXCEPTION_CONTINUE_EXECUTION) {                                                                                                                                                                                                               
     ^~~~~~~~                                                                                                                                                                                                                                                
src/thread.cpp:136:13: error: expected ')' before '(' token                                                                                                                                                                                                  
     __except (EXCEPTION_CONTINUE_EXECUTION) {                                                                                                                                                                                                               
     ~~~~~~~~^~                                                                                                                                                                                                                                              
             )                                                                                                                                                                                                                                               
src/thread.cpp:136:14: error: expected '{' before '(' token                                                                                                                                                                                                  
     __except (EXCEPTION_CONTINUE_EXECUTION) {                                                                                                                                                                                                               
              ^                                                                                                                                                                                                                                              
src/thread.cpp:136:44: error: expected ';' before '{' token                                                                                                                                                                                                  
     __except (EXCEPTION_CONTINUE_EXECUTION) {                                                                                                                                                                                                               
                                            ^~                                                                                                                                                                                                               
                                            ;                          
```


# Environment

* libzmq version (commit hash if unreleased): 
* OS: Docker / openSUSE Leap 15.1

# Minimal test code / Steps to reproduce the issue
Can provide a `Dockerfile` upon request.

**Comment by bluca** [comment]
Interesting that the mingw build test did not catch this:

https://ci.appveyor.com/project/zeromq/libzmq/builds/26024001/job/cp8r6o28y931toy2

Could you please send a PR to fix it?

**Comment by Rush** [comment]
@bluca Sorry, it's obvious why it doesn't compile but I am not a ZeroMQ contributor and not entirely sure why `__except` was used so can't say I know the right fix. 

Fortunately it worked fine with the previous version `4.3.1` and only `4.3.2` is broken.

I can give the fix fix a try if no other person shows up  Perhaps the original author @moretromain  could give this a shot?

I'll be happy to test.

**Comment by TomzBench** [comment]
Not sure if this is related. But I get this error when on "latest_release" branch. So when switching to master and compiling with mingw I get this error...


`C:\...\libzmq\src\thread.cpp:150: error: invalid conversion from 'int (*)(EXCEPTION_RECORD*, void*, CONTEXT*, void*) {aka int (*)(_EXCEPTION_RECORD*, void*, _CONTEXT*, void*)}' to 'void*' [-fpermissive]
     rec.Handler = continue_execution;
                   ^~~~~~~~~~~~~~~~~~`

**Comment by bluca** [comment]
Could you please send a PR to fix it?

**Comment by jakecobb** [comment]
I suspect this change has caused a crash under OpenCppCoverage with Visual Studio builds starting in ZeroMQ 4.3.2:

https://github.com/OpenCppCoverage/OpenCppCoverage/issues/141
