### ISSUE TITLE
4.2.0 won't compile on AIX 7.1

### ISSUE THREAD

**Issue by mbeddo** [zeromq/libzmq#2234]
zeromq 4.1.6 compiles on my AIX box and passes all tests. However, attempting to build zeromq 4.2.0 I find compile problems. Details follow:

$ xlC -qversion
IBM XL C/C++ for AIX, V12.1 (5765-J02, 5725-C72)
Version: 12.01.0000.0000
$ oslevel
7.1.0.0

$ configure CC=xlc CXX=xlC
$ make
Making all in doc
make[1]: Entering directory `/home/meb/zeromq-4.2.0/doc'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/meb/zeromq-4.2.0/doc'
make[1]: Entering directory `/home/meb/zeromq-4.2.0'
  CXX      src/src_libzmq_la-proxy.lo
"src/proxy.cpp", line 157.34: 1540-0217 (S) "rtnevents" is not a member of "struct zmq_pollitem_t".
"src/proxy.cpp", line 188.22: 1540-0217 (S) "rtnevents" is not a member of "struct zmq_pollitem_t".
"src/proxy.cpp", line 189.51: 1540-0217 (S) "rtnevents" is not a member of "struct zmq_pollitem_t".
"src/proxy.cpp", line 197.22: 1540-0217 (S) "rtnevents" is not a member of "struct zmq_pollitem_t".
"src/proxy.cpp", line 198.25: 1540-0217 (S) "rtnevents" is not a member of "struct zmq_pollitem_t".
make[1]: *** [src/src_libzmq_la-proxy.lo] Error 1
make[1]: Leaving directory `/home/meb/zeromq-4.2.0'
make: *** [all-recursive] Error 1

**Comment by bluca** [comment]
Since I don't have access to an AIX system, would you be able to test this fix?

https://github.com/bluca/libzmq/tree/aix_poll

The include order was changed at some point, I suspect that's the issue.

**Comment by mbeddo** [comment]
I get as far as

make[1]: Entering directory `/home/meb/libzmq-aix_poll'
  CXX    src/src_libzmq_la-proxy.lo
"src/proxy.cpp", line 159.34: 1540-0217 (S) "rtnevents" is not a member of "struct zmq_pollitem_t".
"src/proxy.cpp", line 190.22: 1540-0217 (S) "rtnevents" is not a member of "struct zmq_pollitem_t".
"src/proxy.cpp", line 191.51: 1540-0217 (S) "rtnevents" is not a member of "struct zmq_pollitem_t".
"src/proxy.cpp", line 199.22: 1540-0217 (S) "rtnevents" is not a member of "struct zmq_pollitem_t".
"src/proxy.cpp", line 200.25: 1540-0217 (S) "rtnevents" is not a member of "struct zmq_pollitem_t".
make[1]: *** [src/src_libzmq_la-proxy.lo] Error 1
make[1]: Leaving directory `/home/meb/libzmq-aix_poll'
make: *** [all-recursive] Error 1

So this is the same problem (but different line numbers).

However, interestingly, if I export OBJECT_MODE=64 (to build 64 bit code) then the code compiles and the library is built, but ALL of the tests fail with the same error message, reproduced here for one test:

Bad file number (src/signaler.cpp:162)
/bin/sh: 1312030 IOT/Abort trap(coredump)
FAIL: tests/test_system

I think it might be useful to show the relevant contents of the AIX <sys/poll.h> header file? Here is the portion that might be a source of headaches:

…
#ifdef  __64BIT__
/* pollfd.fd is always a 32 bit entity (XOPEN) */
struct  pollfd
{
        int     fd;                     /* file descriptor or file ptr  */
        short   events;                 /* requested events             */
        short   revents;                /* returned events              */

};
#else /* __64BIT__ */
struct  pollfd
{
        long    fd;                     /* file descriptor or file ptr  */
        ushort  reqevents;              /* requested events             */
        ushort  rtnevents;              /* returned events              */
};
#ifndef __HIDE_SVR4_POLLFD_NAMES
#define events  reqevents               /* SVR3,4 pollfd member name    */
#define revents rtnevents               /* SVR3,4 pollfd member name    */
#endif /* __HIDE_SVR4_POLLFD_NAMES */
#endif /* __64BIT__ */
…

**Comment by bluca** [comment]
Thanks, I've seen the snippet on the mailing list, that's definitely what's causing the problem.

Could you please try changing the very first include of poll.h in src/proxy.cpp and src/signaler.cpp from poll.h to sys/poll.h ?

**Comment by mbeddo** [comment]
Hi Luca

There was no improvement when I made the changes. On my AIX box, /usr/include/poll.h only has one line: “#include <sys/poll.h>”

I hacked the makefile to include the “-P” flag so I could see what the structures looked like after the preprocessor. The structure “pollfd” looks like this (32-bit compiling):

struct  pollfd
{
        long    fd;
        ushort  reqevents;
        ushort  rtnevents;
};

Then, of course, there are the macros that define “events” to be “reqevents” and “revents” to be “rtnevents”. So why does the compiler complain that "rtnevents" is not a member of "struct zmq_pollitem_t"? Because it’s not! The definition of zmq_pollitem_t is

typedef struct zmq_pollitem_t
{
    void *socket;
#if defined _WIN32
    SOCKET fd;
#else
    int fd;
#endif
    short events;
    short revents;
} zmq_pollitem_t;

The types don’t match (long vs int, ushort vs short).

I find that “struct pollfd” isn’t actually used in proxy.cpp, so maybe the problem is elsewhere. There must be another place that uses a “struct pollfd” to make AIX system calls and this is somehow mapped onto the zmq_pollitem_t structure which is used everywhere?

I really hate AIX. Nothing’s ever easy.

Strangely, when I compile the codes for 64 bit, the pollfd structure matches the int/short/short members of zmq_pollitem_t and everything builds fine with no warnings or errors, but 72 of 77 tests fail!

**Comment by bluca** [comment]
Ah yes of course, the zmq_pollitem_t members won't match. Fixing it without breaking API and ABI is going to be interesting.

Perhaps adding a conditional \#define at the bottom, something like:

```
typedef struct zmq_pollitem_t
{
    void *socket;
#if defined _WIN32
    SOCKET fd;
#else
    int fd;
#endif
    short events;
    short revents;
#if defined (ZMQ_HAVE_AIX)
#define reqevents events
#define rtnevents revents
#endif
} zmq_pollitem_t;
```

To make things even funnier they are different types, as the 64 bit ones are unsigned short instead of short...
Could you please try this?

Also it was added recently, specifically for AIX use, a different poller implementation: pollset
You might want to try that if it gets you going.

**Comment by mbeddo** [comment]
Code compiles and links, but only 5/77 tests passed. Snippet below:

make  check-TESTS
make[2]: Entering directory `/home/meb/zeromq-4.2.0'
make[3]: Entering directory `/home/meb/zeromq-4.2.0'
PASS: tests/test_ancillaries
./config/test-driver[107]: 5047260 IOT/Abort trap(coredump)
FAIL: tests/test_system
./config/test-driver[107]: 6882788 IOT/Abort trap(coredump)
FAIL: tests/test_pair_inproc
./config/test-driver[107]: 6095392 IOT/Abort trap(coredump)
FAIL: tests/test_pair_tcp
./config/test-driver[107]: 3015096 IOT/Abort trap(coredump)

Not sure I follow your comment about AIX pollset, so not sure what to try next.

**Comment by bluca** [comment]
Is that with the patches or with the pollset?

**Comment by mbeddo** [comment]
Last week I downloaded “aix_poll” from https://github.com/bluca/libzmq/tree/aix_poll. That didn’t work. I then tried your idea:

Perhaps adding a conditional #define at the bottom, something like:

typedef struct zmq_pollitem_t

{

    void *socket;

#if defined _WIN32

    SOCKET fd;

#else

    int fd;

#endif

    short events;

    short revents;

#if defined (ZMQ_HAVE_AIX)

#define reqevents events

#define rtnevents revents

#endif

} zmq_pollitem_t;

And the code compiles and links, but 72/77 tests fail. That’s what I’m reporting on.

I don’t understand what is meant by “with the pollset.”

**Comment by bluca** [comment]
A short while ago an AIX-specific poll implementation was added, so I was wondering if that would help you. You can select it with:

```
./configure --with-poller=pollset
```

**Comment by mbeddo** [comment]
With libzmq-aix_poll, with the new defines in the zmq_pollitem_t structure, and with pollset:

$ configure CC=xlc CXX=xlC --with-poller=pollset
$ make clean
$ make
$ make check
…
make[2]: Leaving directory `/home/meb/libzmq-aix_poll'
make  check-TESTS
make[2]: Entering directory `/home/meb/libzmq-aix_poll'
PASS: tests/test_ancillaries
Bad file number (src/signaler.cpp:162)
/bin/sh: 6621048 IOT/Abort trap(coredump)
FAIL: tests/test_system
Bad file number (src/signaler.cpp:162)
/bin/sh: 2229000 IOT/Abort trap(coredump)
FAIL: tests/test_pair_inproc
Bad file number (src/signaler.cpp:162)
/bin/sh: 6226650 IOT/Abort trap(coredump)
FAIL: tests/test_pair_tcp
…

Result is the same – 72 of 77 tests failed.

**Comment by bluca** [comment]
Could you please run one of the tests manually to see what's the precise error?

```
LD_LIBRARY_PATH=src/.libs tests/.libs/test_pair_tcp
```

(This works on Linux, I hope it works on AIX too!)

Also, could you please do one more try with this branch and see if it still compiles? If it does I'll open a PR so that we can make progress. Once it at least builds then we can continue with the test case failures.

https://github.com/bluca/libzmq/tree/aix_poll

**Comment by mbeddo** [comment]
Using the source code I’ve been working with you on, I run the test and this is what I got.

$ LD_LIBRARY_PATH=src/.libs tests/.libs/test_pair_tcp
Bad file number (src/signaler.cpp:162)
IOT/Abort trap(coredump)
$

I next tried the aix_poll branch you pointed me to. At first, configure complained about missing libsodium, so I reran with

$ configure CC=xlc CXX=xlC –without-libsodium

The library made with a single warning:

  CXX    src/src_libzmq_la-socket_base.lo
"src/socket_base.cpp", line 162.26: 1540-2411 (W) A dynamic cast is present, but the correct RTTI option is not specified.

I tried a “make check” but got this:

  CXX    tests/test_stream_exceeds_buffer.o
"tests/test_stream_exceeds_buffer.cpp", line 16.30: 1540-0274 (S) The name lookup for "AF_INET" did not find a declaration.
"tests/test_stream_exceeds_buffer.cpp", line 16.39: 1540-0274 (S) The name lookup for "SOCK_STREAM" did not find a declaration.
"tests/test_stream_exceeds_buffer.cpp", line 19.38: 1540-0274 (S) The name lookup for "SOL_SOCKET" did not find a declaration.
"tests/test_stream_exceeds_buffer.cpp", line 19.50: 1540-0274 (S) The name lookup for "SO_REUSEADDR" did not find a declaration.
"tests/test_stream_exceeds_buffer.cpp", line 28.10: 1540-0274 (S) The name lookup for "bind" did not find a declaration.
"tests/test_stream_exceeds_buffer.cpp", line 30.10: 1540-0274 (S) The name lookup for "listen" did not find a declaration.
"tests/test_stream_exceeds_buffer.cpp", line 40.23: 1540-0274 (S) The name lookup for "accept" did not find a declaration.
"tests/test_stream_exceeds_buffer.cpp", line 46.10: 1540-0274 (S) The name lookup for "send" did not find a declaration.
make[2]: *** [tests/test_stream_exceeds_buffer.o] Error 1
make[2]: Leaving directory `/home/meb/libzmq'
make[1]: *** [check-am] Error 2
make[1]: Leaving directory `/home/meb/libzmq'
make: *** [check-recursive] Error 1

But since the “make check” built test_pair_tcp I decided to try that:

$ LD_LIBRARY_PATH=src/.libs tests/.libs/test_pair_tcp
$

So it seemed to work (?).

**Comment by bluca** [comment]
Ok, let's take it one bit at a time. Since the last version of the branch gives you a build and a test pass I'll start with that.

Once it's merged, we can go on.

Thanks for the assistance!

**Comment by bluca** [comment]
Ok, could you please try from libzmq/master and see where we are now?

**Comment by mbeddo** [comment]
While making, the only warning is:

  CXX    src/src_libzmq_la-socket_base.lo
"src/socket_base.cpp", line 162.26: 1540-2411 (W) A dynamic cast is present, but the correct RTTI option is not specified.

While “make check” the error(s) are:

  CXX    tests/test_stream_exceeds_buffer.o
"tests/test_stream_exceeds_buffer.cpp", line 16.30: 1540-0274 (S) The name lookup for "AF_INET" did not find a declaration.
"tests/test_stream_exceeds_buffer.cpp", line 16.39: 1540-0274 (S) The name lookup for "SOCK_STREAM" did not find a declaration.
"tests/test_stream_exceeds_buffer.cpp", line 19.38: 1540-0274 (S) The name lookup for "SOL_SOCKET" did not find a declaration.
"tests/test_stream_exceeds_buffer.cpp", line 19.50: 1540-0274 (S) The name lookup for "SO_REUSEADDR" did not find a declaration.
"tests/test_stream_exceeds_buffer.cpp", line 28.10: 1540-0274 (S) The name lookup for "bind" did not find a declaration.
"tests/test_stream_exceeds_buffer.cpp", line 30.10: 1540-0274 (S) The name lookup for "listen" did not find a declaration.
"tests/test_stream_exceeds_buffer.cpp", line 40.23: 1540-0274 (S) The name lookup for "accept" did not find a declaration.
"tests/test_stream_exceeds_buffer.cpp", line 46.10: 1540-0274 (S) The name lookup for "send" did not find a declaration.

If I remove “test_stream_exceeds_buffer” from the Makefile, the code goes on to run the remaining tests. All but 2 of the remaining tests PASSED! The ones that didn’t pass:

…
libsodium not installed, skipping CURVE test
…
/bin/sh: 5637200 Segmentation fault(coredump)
FAIL: tests/test_many_sockets
…
/bin/sh: 5047070 Alarm clock
FAIL: tests/test_shutdown_stress

For the “test_shutdown_stress” failure, the error message is:

$ LD_LIBRARY_PATH=src/.libs tests/.libs/test_shutdown_stress
Assertion failed: false (src/object.cpp:400)
IOT/Abort trap(coredump)

I’m not sure what “sodium” is, but I wonder whether we need it for our application? We will be using 0MQ behind our corporate firewall.

Nice work!

**Comment by bluca** [comment]
test_shutdown_stress and test_many_sockets are very resource-dependent so I wouldn't worry too much if they fail.

You could try to increase the limit of per-process file descriptors with:

```
ulimit -n 64000
```

And see if that helps.

For test_stream_exceeds_buffer I think some includes are missing (again!), could you please try from my branch:

https://github.com/bluca/libzmq/tree/aix_test

For libsodium, it's a library to provide encryption functionality to be used with ZMQ_CURVE. You do not need it if you are not going to use CURVE encryption. Also there is an internal implementation with tweetnacl, but for enterprise usage it's recommended to use libsodium as distributed by the supported platform in use.

**Comment by mbeddo** [comment]
CXX    src/src_libzmq_la-socket_base.lo
"src/socket_base.cpp", line 162.26: 1540-2411 (W) A dynamic cast is present, but the correct RTTI option is not specified.

The tests compiled and linked ok, but they all failed. ☹

**Comment by bluca** [comment]
I can't see how that diff could make the tests fail, that is very strange...

What's the error if you run one manually?

**Comment by mbeddo** [comment]
I’m new to git (long time user of cvs). So just to make sure I rebuilt and tested master:


1)      Browser to https://github.com/bluca/libzmq/tree/master

2)      Click on green button (“Clone or download”) and I use “Download ZIP”

3)      Autogen.sh, configure, make, make clean

Same compile warning and 2 failed tests that I reported previously.

Then I went to https://github.com/bluca/libzmq/tree/aix_test and followed steps 2 and 3 above. Same compile warning but library builds, but now ALL tests fail.

Running one test manually:

$ LD_LIBRARY_PATH=src/.libs tests/.libs/test_pair_tcp
Bad file number (src/signaler.cpp:162)
IOT/Abort trap(coredump)

Hmm?

**Comment by bluca** [comment]
Ah, my master branch is extremely out of date as I don't use it.

This means the tests used to work, but at some point between today and the 16th of December 2015 they broke. This is going to be fun :-)

It's complaining that the signaler file descriptor is invalid. I can't see why, I'll try to have a look.

**Comment by mbeddo** [comment]
Sorry about the mixup. I just now did a “git clone https://github.com/zeromq/libzmq.git” which I think is the “master” you originally intended earlier? The code built fine but 79 of 85 tests failed. All in same spot: “Bad file number (src/signaler.cpp:162)”. That’s as much info as running a test manually gives.

**Comment by bluca** [comment]
Ok, could you please do a git pull and try again? I fixed more headers

**Comment by bluca** [comment]
@hnwyllmm you did some work on AIX, any chance you could please help us with this issue?

**Comment by mbeddo** [comment]
Git pull from https://github.com/zeromq/libzmq.git? If so, it compiles and 79 of 85 tests fail.

**Comment by bluca** [comment]
Ok, so at least it builds now :-)

I don't really know why the tests are reporting a bad file descriptor, I hope @hnwyllmm can help us

**Comment by hnwyllmm** [comment]
sorry for the late reponse. I forget to check the email.
In mine test, the test_pair_tcp is running fine.
Here are the flags used with configure
```
export CFLAGS=-q64
export CXXFLAGS=-q64
export CC=xlc_r
export CXX=xlC_r
export LDFLAGS="-brtl -q64"
export NM="nm -X64"
export AR="ar -X64"
```
But there are other failure, such as test_req_correlate, test_inproc_connect and test_getsockopt_memset and so on.

**Comment by hnwyllmm** [comment]
closed by #2251 
All of test cases passed.
NOTE: you should use **LIBPATH** instead of LD_LIBRARY_PATH on AIX

**Comment by bluca** [comment]
Thanks! @mbeddo  let us know if the latest version of master fixed the problem for you add well

**Comment by mbeddo** [comment]
From https://github.com/zeromq/libzmq.git, and using the flags (64-bit build)


export CFLAGS=-q64

export CXXFLAGS=-q64

export CC=xlc_r

export CXX=xlC_r

export LDFLAGS="-brtl -q64"

export NM="nm -X64"

export AR="ar -X64"

for configure, one test failed:

Assertion failed: rc == 0, file  tests/test_unbind_wildcard.cpp, line 36
/bin/sh: 40239272 IOT/Abort trap(coredump)
FAIL: tests/test_unbind_wildcard

However, when I re-ran “make check” ALL tests passed. We have a developer working to incorporate zeromq into our processes, perhaps he had a socket bound while I was testing?


-          Mike

**Comment by bluca** [comment]
It could be. I'm glad all works now, sorry it took a while :-)

Since it's all building and all tests are passing I'm closing this now. Please open a new issue if you find other problems.
