### ISSUE TITLE
Build Error for ZMQ 4.2.5

### ISSUE THREAD

**Issue by James-Castles** [zeromq/libzmq#3042]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
@bluca 
When build ZMQ 4.2.5, I meet some errors ,

# Environment

* libzmq version (4.2.5): 
* OS: 
linux
# Minimal test code / Steps to reproduce the issue

1.  When build it using command  :  

./configure --host=arm-brcm-linux-gnueabi --prefix=$LO_SDK_TOP_DIR       \
                LIBS=-L$LO_SDK_LIB_DIR --with-relaxed                 && \
    make && make install || (cat config.log && exit 1)

It stops when meet errors as below :  

# What's the actual result? (include assertion message & call stack if applicable)

_configure: WARNING: unrecognized options: --with-relaxed
Making all in doc
make[1]: Entering directory `/tmp/src/zeromq-4.2.5/doc'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/tmp/src/zeromq-4.2.5/doc'
make[1]: Entering directory `/tmp/src/zeromq-4.2.5'
  CC       external/unity/unity.o
  AR       external/unity/libunity.a
  CXX      src/src_libzmq_la-address.lo
cc1plus: warnings being treated as errors
In file included from src/ypipe.hpp:33,
                 from src/mailbox.hpp:39,
                 from src/ctx.hpp:38,
                 from src/address.cpp:33:
src/atomic_ptr.hpp: In member function 'void zmq::atomic_value_t::store(int)':
src/atomic_ptr.hpp:252: warning: dereferencing type-punned pointer will break strict-aliasing rules
src/atomic_ptr.hpp: In member function 'int zmq::atomic_value_t::load() const':
src/atomic_ptr.hpp:266: warning: dereferencing type-punned pointer will break strict-aliasing rules
src/atomic_ptr.hpp:271: error: invalid initialization of reference of type 'zmq::mutex_t&' from expression of type 'const zmq::mutex_t'
src/atomic_ptr.hpp:123: error: in passing argument 4 of 'void* zmq::atomic_cas(void* volatile*, void*, void*, zmq::mutex_t&)'
make[1]: *** [src/src_libzmq_la-address.lo] Error 1
make: *** [all-recursive] Error 1
make[1]: Leaving directory `/tmp/src/zeromq-4.2.5'
This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake._

# What's the expected result?
Complete the build with successful result.

Thank you.

**Comment by bluca** [comment]
What are the compiler, libc and libstdc++ versions?

**Comment by James-Castles** [comment]
Hi bluca， Version information as below:
libc-2.5.so 
libc.so.6 
libform.so.5.6
libmenu.so.5
libnsl.so.1
libnss_hesiod.so.2 
libpanel.so.5.6
libSegFault.so
libstdc++.so.6.0.9

Thank you

**Comment by korbes** [comment]
I have the same problem with the compiler arm-bcm2708-linux-gnueabi, from the raspberry pi tools: https://github.com/raspberrypi/tools/tree/master/arm-bcm2708/arm-bcm2708-linux-gnueabi.

The problems was introduced in #2910. If ZMQ_ATOMIC_PTR_MUTEX is defined, the mutex_t in line 286 needs to be mutable (as is for VxWorks) because load() is const and passes it as non-const to atomic_cas.

**Comment by bluca** [comment]
Fixed by https://github.com/zeromq/libzmq/pull/3112
